# Estas são as plataformas de modelo de financiamento suportadas.

github: 
  - alemaodacapa

patreon: 
  alemaodacapa_patreon

ko_fi: 
  alemaodacapa_ko-fi

buy_me_a_coffee: 
  alemaodacapa_bmc

custom: 
  - 'https://pay.hotmart.com/Y95202654S'  # Link para Hotmart
  - 'https://api.whatsapp.com/send/?phone=5511948793902'  # Link do WhatsApp
  - 'https://bipa.app/0d3e7f69-0797-4fa6-8d51-3407e4ce6aa6'  # Endereço de Bitcoin na Bipa
  - 'alemaodacapa@bipa.app'  # Endereço de Bitcoin Bipa Bitcoin Pix
